<!DOCTYPE html>
<html lang="he">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>חיפוש זמני שבת לפי מיקום</title>
    <script>
        const shabbatTimes = {
            "ירושלים": {"כניסה": "16:55", "יציאה": "18:07", "lat": 31.7683, "lon": 35.2137},
            "תל אביב": {"כניסה": "17:11", "יציאה": "18:09", "lat": 32.0853, "lon": 34.7818},
            "חיפה": {"כניסה": "17:04", "יציאה": "18:08", "lat": 32.7940, "lon": 34.9896}
        };

        function getUserLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(position => {
                    findClosestCity(position.coords.latitude, position.coords.longitude);
                }, () => {
                    document.getElementById("result").innerText = "לא ניתן לאתר את מיקומך.";
                });
            } else {
                document.getElementById("result").innerText = "הדפדפן שלך אינו תומך במיקום גיאוגרפי.";
            }
        }

        function findClosestCity(userLat, userLon) {
            let closestCity = "";
            let minDistance = Infinity;

            Object.keys(shabbatTimes).forEach(city => {
                let cityData = shabbatTimes[city];
                let distance = Math.sqrt(
                    Math.pow(userLat - cityData.lat, 2) +
                    Math.pow(userLon - cityData.lon, 2)
                );
                if (distance < minDistance) {
                    minDistance = distance;
                    closestCity = city;
                }
            });

            const times = shabbatTimes[closestCity];
            document.getElementById("result").innerHTML = `העיר הקרובה ביותר: ${closestCity}<br>
                זמני כניסת שבת: ${times["כניסה"]}<br>
                זמני יציאת שבת: ${times["יציאה"]}`;
        }
    </script>
</head>
<body>
    <h1>חיפוש זמני שבת</h1>
    <button onclick="getUserLocation()">מצא זמני שבת לפי מיקום</button>
    <p id="result"></p>
</body>
</html>
